namespace TestDynamicListLayout.Data
{
    public class AssetInfo
    {
        public int RowId { get; set; }
        public int AssetId { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public int AssetTypeId { get; set; }
        public int AssetCurrencyId { get; set; }
        public int StatusId { get; set; }
        public string ISIN { get; set; }
        public string Ticker { get; set; }
        public string Comment { get; set; }
        public string CreatedUserName { get; set; }
        public DateTime? CreationDate { get; set; }
        public string ModifiedUserName { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? AssetIdGUID { get; set; }
        public bool Managed { get; set; }
        public DateTime? ClosedDate { get; set; }
        public int? ExclusivityIIC { get; set; }
        public int? CashTypeId { get; set; }
        public DateTime? WatermarkInitialDate { get; set; }
        public decimal? WatermarkInitialValue { get; set; }
        public int? WatermarkReferredIndex { get; set; }
        public int BV_ItemId { get; set; }
        public bool? BV_1 { get; set; }
        public string BV_28 { get; set; }
        public bool? BV_46 { get; set; }
        public string BV_56 { get; set; }
        public string BV_57 { get; set; }
        public decimal? BV_58 { get; set; }
        public string BV_59 { get; set; }
        public string BV_60 { get; set; }
        public string BV_61 { get; set; }
        public decimal? BV_62 { get; set; }
        public decimal? BV_63 { get; set; }
        public decimal? BV_65 { get; set; }
        public string BV_66 { get; set; }
        public string BV_67 { get; set; }
        public string BV_68 { get; set; }
        public string BV_69 { get; set; }
        public string BV_70 { get; set; }
        public bool? BV_72 { get; set; }
        public string BV_77 { get; set; }
        public decimal? BV_85 { get; set; }
        public string BV_86 { get; set; }
        public string BV_87 { get; set; }
        public string BV_88 { get; set; }
        public decimal? BV_90 { get; set; }
        public decimal? BV_93 { get; set; }
        public string BV_94 { get; set; }
        public bool? BV_95 { get; set; }
        public string BV_97 { get; set; }
        public decimal? BV_98 { get; set; }
        public bool? BV_99 { get; set; }
        public bool? BV_105 { get; set; }
        public string BV_106 { get; set; }
        public string BV_163 { get; set; }
        public string BV_170 { get; set; }
        public decimal? BV_171 { get; set; }
        public decimal? BV_172 { get; set; }
        public bool? BV_173 { get; set; }
        public string? BV_175 { get; set; }
        public string BV_176 { get; set; }
        public bool? BV_177 { get; set; }
        public string BV_178 { get; set; }
        public decimal? BV_180 { get; set; }
        public string BV_181 { get; set; }
        public decimal? BV_184 { get; set; }
        public string BV_186 { get; set; }
        public decimal? BV_187 { get; set; }
        public decimal? BV_188 { get; set; }
        public decimal? BV_189 { get; set; }
        public string BV_192 { get; set; }
        public string BV_194 { get; set; }
        public string BV_195 { get; set; }
        public string BV_200 { get; set; }
        public string BV_201 { get; set; }
        public string BV_202 { get; set; }
        public string BV_203 { get; set; }
        public string BV_204 { get; set; }
        public string BV_245 { get; set; }
        public string BV_249 { get; set; }
        public string BV_254 { get; set; }
        public string BV_255 { get; set; }
        public string BV_256 { get; set; }
        public decimal? BV_257 { get; set; }
        public decimal? BV_258 { get; set; }
        public string BV_259 { get; set; }
        public string BV_260 { get; set; }
        public string BV_261 { get; set; }
        public string BV_262 { get; set; }
        public string BV_263 { get; set; }
        public bool? BV_265 { get; set; }
        public string BV_271 { get; set; }
        public string BV_272 { get; set; }
        public decimal? BV_273 { get; set; }
        public string BV_274 { get; set; }
        public string BV_275 { get; set; }
        public string BV_276 { get; set; }
        public string BV_277 { get; set; }
        public string BV_278 { get; set; }
        public string BV_279 { get; set; }
        public string BV_280 { get; set; }
        public string BV_281 { get; set; }
        public string BV_282 { get; set; }
        public string BV_283 { get; set; }
        public string BV_284 { get; set; }
        public string BV_285 { get; set; }
        public string BV_287 { get; set; }
        public string BV_288 { get; set; }
        public string BV_289 { get; set; }
        public string BV_290 { get; set; }
        public decimal? BV_291 { get; set; }
        public string BV_300 { get; set; }
        public string BV_301 { get; set; }
        public string BV_302 { get; set; }
        public string BV_303 { get; set; }
        public string BV_304 { get; set; }
        public string BV_305 { get; set; }
        public string BV_306 { get; set; }
        public string BV_307 { get; set; }
        public string BV_308 { get; set; }
        public string BV_309 { get; set; }
        public string BV_310 { get; set; }
        public string BV_311 { get; set; }
        public string BV_312 { get; set; }
        public string BV_313 { get; set; }
        public string BV_314 { get; set; }
        public string BV_315 { get; set; }
        public string BV_316 { get; set; }
        public string BV_317 { get; set; }
        public string BV_318 { get; set; }
        public string BV_319 { get; set; }
        public string BV_321 { get; set; }
        public string BV_1000002 { get; set; }
        public string BV_1000013 { get; set; }
        public string BV_1000025 { get; set; }
        public string BV_1000028 { get; set; }
        public string BV_1000031 { get; set; }
        public string BV_1000032 { get; set; }
        public bool IsItemActive { get; set; }
        public bool IsClass { get; set; }
        public decimal? LastPrice { get; set; }
        public DateTime? LastPriceDate { get; set; }
        public decimal? InitialAmountYTD { get; set; }
        public decimal? FinalAmountYTD { get; set; }
        public decimal? InOutYTD { get; set; }
        public decimal? GainsYTD { get; set; }
        public decimal? PerformanceYTD { get; set; }
        public DateTime? InitialDateYTD { get; set; }
        public DateTime? FinalDateYTD { get; set; }
        public int NumDaysYTD { get; set; }
        public decimal WeightedYTD { get; set; }
        public decimal InitialAmountD1 { get; set; }
        public decimal FinalAmountD1 { get; set; }
        public decimal InOutD1 { get; set; }
        public decimal GainsD1 { get; set; }
        public decimal PerformanceD1 { get; set; }
        public DateTime? InitialDateD1 { get; set; }
        public DateTime? FinalDateD1 { get; set; }
        public int NumDaysD1 { get; set; }
        public decimal WeightedD1 { get; set; }
        public decimal InitialAmountMTD { get; set; }
        public decimal FinalAmountMTD { get; set; }
        public decimal InOutMTD { get; set; }
        public decimal GainsMTD { get; set; }
        public decimal PerformanceMTD { get; set; }
        public DateTime? InitialDateMTD { get; set; }
        public DateTime? FinalDateMTD { get; set; }
        public int NumDaysMTD { get; set; }
        public decimal WeightedMTD { get; set; }
        public decimal InitialAmountM12 { get; set; }
        public decimal FinalAmountM12 { get; set; }
        public decimal InOutM12 { get; set; }
        public decimal GainsM12 { get; set; }
        public decimal PerformanceM12 { get; set; }
        public DateTime? InitialDateM12 { get; set; }
        public DateTime? FinalDateM12 { get; set; }
        public int NumDaysM12 { get; set; }
        public decimal WeightedM12 { get; set; }
    }

}
